# H2
spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/squirrel
    url: jdbc:h2:tcp://localhost/~/squirrel # 메모리 내 데이터베이스 URL
    driver-class-name: org.h2.Driver # H2 드라이버 클래스
    username: sa # 기본 사용자 이름
    password: # 기본 비밀번호는 비워둡니다.
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  hibernate:
    ddl-auto: update
  sql:
    init:
#      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)

# RDS
#spring:
#  profiles:
#    include: SECRET-KEY
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{RDS 엔드포인트}:3306/$db
#    username: admin
#    password:
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true

  # healthcheck
  # BaseURL/actuator/health
  management:
    endpoints:
      web:
        base-path: # 기본값 /actuator
        path-mapping:
          health: # 기본값 /health
    endpoint:
      health:
        show-details: always